<a href="https://colab.research.google.com/github/jihan4540/2025-1-myclass-BDA/blob/main/inclass/03w_B_wed_0319_dataframe_application.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

03 주차 수업

## 데이터프레임 정보와 수정

In [3]:
!git clone http://github.com/ai7dnn/data

Cloning into 'data'...
warning: redirecting to https://github.com/ai7dnn/data/
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 20 (delta 3), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (20/20), 2.12 MiB | 5.95 MiB/s, done.
Resolving deltas: 100% (3/3), done.

In [7]:
import pandas as pd

df = pd.read_csv('data/2016년졸음운전.csv' , encoding='euc-kr')
df

          연월  사고(건)  사망(명)  부상(명)
0    2016년1월    192      5    387
1    2016년2월    174      6    328
2    2016년3월    217      7    435
3    2016년4월    216      7    419
4    2016년5월    239     13    522
5    2016년6월    200     12    362
6    2016년7월    227      9    460
7    2016년8월    230      7    490
8    2016년9월    187     13    347
9   2016년10월    183     10    367
10  2016년11월    200      5    418
11  2016년12월    168      4    364

In [ ]:
df = pd.read_csv('data/2016년졸음운전.csv' , encoding='euc-kr', ind)
df

In [8]:
df.dtypes

연월       object
사고(건)     int64
사망(명)     int64
부상(명)     int64
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   연월      12 non-null     object
 1   사고(건)   12 non-null     int64
 2   사망(명)   12 non-null     int64
 3   부상(명)   12 non-null     int64
dtypes: int64(3), object(1)
memory usage: 516.0+ bytes

In [12]:
df.describe()

            사고(건)      사망(명)       부상(명)
count   12.000000  12.000000   12.000000
mean   202.750000   8.166667  408.250000
std     23.014324   3.186144   60.051682
min    168.000000   4.000000  328.000000
25%    186.000000   5.750000  363.500000
50%    200.000000   7.000000  402.500000
75%    219.500000  10.500000  441.250000
max    239.000000  13.000000  522.000000

In [13]:
df.sum()

연월       2016년1월2016년2월2016년3월2016년4월2016년5월2016년6월2016...
사고(건)                                                 2433
사망(명)                                                   98
부상(명)                                                 4899
dtype: object

In [15]:
df[['사고(건)', '사망(명)', '부상(명)']].sum(axis=1)
# Selects only the numerical columns and performs the sum across rows.

0     584
1     508
2     659
3     642
4     774
5     574
6     696
7     727
8     547
9     560
10    623
11    536
dtype: int64

In [19]:
df.max()

연월       2016년9월
사고(건)        239
사망(명)         13
부상(명)        522
dtype: object

In [20]:
df.max(axis=0)

연월       2016년9월
사고(건)        239
사망(명)         13
부상(명)        522
dtype: object

In [23]:
df.min()

연월       2016년10월
사고(건)         168
사망(명)           4
부상(명)         328
dtype: object

In [24]:
df.min(axis=0)

연월       2016년10월
사고(건)         168
사망(명)           4
부상(명)         328
dtype: object

In [ ]:
df.min(axis=None)

In [26]:
df

          연월  사고(건)  사망(명)  부상(명)
0    2016년1월    192      5    387
1    2016년2월    174      6    328
2    2016년3월    217      7    435
3    2016년4월    216      7    419
4    2016년5월    239     13    522
5    2016년6월    200     12    362
6    2016년7월    227      9    460
7    2016년8월    230      7    490
8    2016년9월    187     13    347
9   2016년10월    183     10    367
10  2016년11월    200      5    418
11  2016년12월    168      4    364

In [ ]:
df[['사망(명)', '부상(명)']].sum(axis=1)

In [ ]:
df.iloc[:.1:].sum(axis=1)

In [41]:
df2 = df.copy()
df2['재해자수'] = df[['사망(명)', '부상(명)']].sum(axis=1)
df2

          연월  사고(건)  사망(명)  부상(명)  재해자수
0    2016년1월    192      5    387   392
1    2016년2월    174      6    328   334
2    2016년3월    217      7    435   442
3    2016년4월    216      7    419   426
4    2016년5월    239     13    522   535
5    2016년6월    200     12    362   374
6    2016년7월    227      9    460   469
7    2016년8월    230      7    490   497
8    2016년9월    187     13    347   360
9   2016년10월    183     10    367   377
10  2016년11월    200      5    418   423
11  2016년12월    168      4    364   368

In [42]:
df2.loc['총계'] = df2.sum(axis=0)
df2

,연월,사고(건),사망(명),부상(명),재해자수
0,2016년1월,192,5,387,392
1,2016년2월,174,6,328,334
2,2016년3월,217,7,435,442
3,2016년4월,216,7,419,426
4,2016년5월,239,13,522,535
5,2016년6월,200,12,362,374
6,2016년7월,227,9,460,469
7,2016년8월,230,7,490,497
8,2016년9월,187,13,347,360
9,2016년10월,183,10,367,377
10,2016년11월,200,5,418,423
11,2016년12월,168,4,364,368
총계,2016년1월2016년2월2016년3월2016년4월2016년5월2016년6월2016...,2433,98,4899,4997

In [43]:
df2

,연월,사고(건),사망(명),부상(명),재해자수
0,2016년1월,192,5,387,392
1,2016년2월,174,6,328,334
2,2016년3월,217,7,435,442
3,2016년4월,216,7,419,426
4,2016년5월,239,13,522,535
5,2016년6월,200,12,362,374
6,2016년7월,227,9,460,469
7,2016년8월,230,7,490,497
8,2016년9월,187,13,347,360
9,2016년10월,183,10,367,377
10,2016년11월,200,5,418,423
11,2016년12월,168,4,364,368
총계,2016년1월2016년2월2016년3월2016년4월2016년5월2016년6월2016...,2433,98,4899,4997

In [44]:
df2[ [True]*6 + [False]*7 ]

        연월  사고(건)  사망(명)  부상(명)  재해자수
0  2016년1월    192      5    387   392
1  2016년2월    174      6    328   334
2  2016년3월    217      7    435   442
3  2016년4월    216      7    419   426
4  2016년5월    239     13    522   535
5  2016년6월    200     12    362   374

In [45]:
df2['재해자수'] > 400

0     False
1     False
2      True
3      True
4      True
5     False
6      True
7      True
8     False
9     False
10     True
11    False
총계     True
Name: 재해자수, dtype: bool

In [46]:
df['사망(명)'] == 7

0     False
1     False
2      True
3      True
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
Name: 사망(명), dtype: bool

In [47]:
df['사망(명)'].isin([7,10])

0     False
1     False
2      True
3      True
4     False
5     False
6     False
7      True
8     False
9      True
10    False
11    False
Name: 사망(명), dtype: bool

In [49]:
df[ (df['사망(명)'].isin([7,10])) | (df['부상(명)'] > 350) ]

          연월  사고(건)  사망(명)  부상(명)
0    2016년1월    192      5    387
2    2016년3월    217      7    435
3    2016년4월    216      7    419
4    2016년5월    239     13    522
5    2016년6월    200     12    362
6    2016년7월    227      9    460
7    2016년8월    230      7    490
9   2016년10월    183     10    367
10  2016년11월    200      5    418
11  2016년12월    168      4    364

In [55]:
df2[df2.index.str.contains('3')]

ValueError: Cannot mask with non-boolean array containing NA / NaN values